### ISSUE TITLE
Invalid or corrupted pad block

### ISSUE THREAD

**Issue by indranildutta06** [Noobware1/crypto_dart#3]
This issue occurred while decrypting ciphers made in other platforms (Java). Due to an incorrect calculation of blockSize, inputPad was set to the wrong value. Hence, relying on the user-given `blockLength` is necessary to address correct encryption/decryption.

The current version 1.0.2 implementation has a parameter `blockLength` that's unused internally. Instead of using that, `keySize * digest.digestSize` is getting used and that is creating a wrong `inputPad` resulting error while decryption.

If this library has encrypted any value, it can be decrypted because it follows the same error while encryption and decryption. Still, if the encrypted text is made on another platform such as Java (using `javax.crypto`) then it's failing due to incorrect blockLength used in input padding.

Below is the decryption logic:

```
String decryptText(text) {
    try {
      if (text != null) {
        var asciiText = utf8.decode(base64.decode(text));
        if (asciiText.split(kSeparator).length == 3) {
          var asciiTextArr = asciiText.split(kSeparator);
          var iv = asciiTextArr[0];
          var salt = asciiTextArr[1];
          var cipherTextEncoded = asciiTextArr[2];
          var cipherText = base64.decode(cipherTextEncoded);

          var key = CryptoDart.PBKDF2(
              key: passPhrase,
              salt: CryptoDart.enc.HEX.parse(salt),
              keySize: 4,
              hasher: HashAlgorithms.SHA1,
              blockLength: 64,
              iterations: 1000);
          var decrypted = CryptoDart.AES.decrypt(cipherText, key,
              options: CipherOptions(
                  iv: CryptoDart.enc.HEX.parse(iv),
                  mode: Mode.cbc,
                  padding: Padding.PKCS7));
          return utf8.decode(decrypted);
        } else {
          return text;
        }
      } else {
        return text;
      }
    } catch (error) {
      debug_log.log("decryptText: $error");
      return text;
    }
  }
```

I've given a fix to correct the issue and raised a [pull request](https://github.com/Noobware1/crypto_dart/pull/2)

**Comment by Noobware1** [comment]
Wow people actually use this package?? I created it for personal use only but thank you for showing your support 💙.
blockLength parameter was used previously but I stopped using that and started to follow how cryptojs does rather than how java does it.

I understand your problem since this project doesn't follow crypto js fully this issue was raised so, I'll accept your solution for now.

**Comment by indranildutta06** [comment]
Hi,

Thanks for replying me back and merging so quickly. The package is pretty
good and nicely implemented. It's a more complete package than the others
available in the pub library.

Can you please publish 1.0.3 with the latest changes in pub.dev? It'd be
helpful.

Thanks & Regards

Indranil Dutta

*Lead Organizer, GDG Kolkata <https://gdg.community.dev/gdg-kolkata/>*
*Mobile:* (+91)9038889013
*Email:* ***@***.***
*Skype Id:* indranildutta.6
*Hello Indranil <https://indranildutta.netlify.app/>*

**Comment by Noobware1** [comment]
I have updated the package at pub but I have now implemented the same way that crypto-js use to figure out block length but it can cause problems if the Digest.blockSize is different than that of crypto-js so, that's why now I have made blockLength from user optional just in case for issues like this.

also could you test it without giving the PBKDF2 function blockLength so I can know if it works?
